[tool.pyright]
venvPath = "."
venv = ".venv-1"
useLibraryCodeForTypes = false

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-ra -q"
asyncio_default_fixture_loop_scope = "function"
testpaths = [
    "agents",
    "autonomous-coding"
]
norecursedirs = [
    ".venv",
    ".venv-1",
    ".venv2",
    "computer-use-demo",
    "watson-glaser-trainer",
    "node_modules",
    ".git"
]
